language: java
jdk:
- oraclejdk8
env:
  global:
      - HEROKU_API_KEY: 86e10672-cedc-4769-aba1-c7100d27ba81
before_install: cd spark-uutislukija; git clone https://github.com/horttanainen/PaivanUutiset.git;
  mvn clean install -U -f PaivanUutiset/pom.xml; git clone https://github.com/horttanainen/HackerNewsUutiset.git;
  mvn clean install -U -f HackerNewsUutiset/pom.xml;
after_success:
- mvn clean cobertura:cobertura coveralls:report heroku:deploy
